[EN-5707] feat(outsourcing): BO coach externe
ReseauEntourage/entourage-job-front pull request #110
Opened 2023-05-25 15:25 UTC by PaulEntourage

2023-05-31 10:04 UTC, emile-bex requested changes

2023-05-31 10:04 UTC, emile-bex commented on src/pages/backoffice/parametres.tsx
> +                  // }}
Pourquoi on modifie la condition et on enlève le `onChange` ?

2023-05-31 12:39 UTC, PaulEntourage commented on .eslintrc.json
> +    "import/no-self-import": "off",
Non, ca concerne 
`export const IconNoSSR = dynamic(
  () => {
    return import('src/components/utils/Icon');
  },
  { ssr: false }
);`

2023-05-31 13:09 UTC, PaulEntourage commented on src/components/Footer.tsx
> +                              childrenChildrenIndex: any
idem

2023-05-31 13:11 UTC, PaulEntourage commented on src/components/backoffice/LayoutBackOffice.tsx
> +  isEmpty,
idem

2023-05-31 13:16 UTC, PaulEntourage commented on src/components/backoffice/admin/members/MemberList/useRole.ts
> +export function useRole(): UserRole {
Oui t'as raison, mais il est exclusivement utilisé comme une chaine de caractères dans le reste du code. Du coup tu suggères qu'on modifie le type et qu'on destructure? ou bien qu'on force le typage comme je l'ai fait. Tel quel, ca fonctionne bien, mais on peut choisir la première solution.

2023-05-31 13:23 UTC, PaulEntourage commented on src/components/backoffice/candidate/CandidateOpportunities/CandidateOffersTab/CandidateOffersTab.tsx
> +    recommanded: string;
Je ne sais plus honnêtement et ca ne semble pas poser de souci de TS à la suppression, donc je retire.

2023-05-31 13:25 UTC, PaulEntourage commented on src/components/backoffice/candidate/CandidateOpportunities/CandidateOpportunities.utils.tsx
>  export const textVariables = {
Okay done

2023-05-31 13:26 UTC, PaulEntourage commented on src/components/backoffice/candidate/ExternalCoach/ExternalCoachMemberList.tsx
> +import { MemberColumn } from '../../admin/members/MemberTable/Member/Member.types';
Bien vu, merci, corrigé

2023-05-31 13:26 UTC, PaulEntourage commented on src/components/backoffice/candidate/CandidateOpportunities/CandidateOpportunities.tsx
> +      recommanded: string;
Idem

2023-05-31 14:02 UTC, PaulEntourage commented on src/components/backoffice/opportunities/OpportunitiesContainer/NoOpportunities/NoOpportunities.tsx
> +          href={`/backoffice/candidat${candidateId}/offres/public`}
Bien vu !

2023-05-31 14:05 UTC, PaulEntourage commented on src/components/backoffice/opportunities/OpportunitiesContainer/OpportunityDetails/CandidateOpportunityDetails/CandidateOpportunityDetailsCTAs/CandidateOpportunityDetailsCTAs.tsx
> +            const queryParams: any = {};
Done

2023-05-31 14:08 UTC, PaulEntourage commented on src/components/backoffice/opportunities/useCandidateId.ts
> +    return getCandidateIdFromCoachOrCandidate(user)[0] as string;
Non, parce qu'il faut un candidateId pour cette fonction, et là on est dans le cas où on n'a pas le candidateId.

2023-05-31 14:15 UTC, PaulEntourage commented on src/components/filters/SearchBar.tsx
> +          // filters={filters}
Tu verras que dans le composant FiltersMobile, on n'a pas de prop appelée "filters". Je l'ai commenté au cas où.

2023-05-31 14:16 UTC, PaulEntourage commented on src/components/filters/SearchBar.tsx
> +            // search={search}
Idem, le composant FiltersOptions ne prend pas ces props.

2023-05-31 14:17 UTC, PaulEntourage commented on src/components/filters/SearchBar.tsx
> +  // numberOfResults,
Parce qu'il n'était passé que dans les composants ci-dessus qui ne prennent pas cette prop ;)

2023-05-31 14:21 UTC, PaulEntourage commented on src/components/forms/FormWithValidation.tsx
> +  };
J'ai passé le AnyToFix, mais je préfère traiter ça à part entière dans un ticket full TS

2023-05-31 14:23 UTC, PaulEntourage commented on src/components/forms/FormWithValidation.tsx
> +                        // }}
Si tu check le fichier du composant, InputsContainer.tsx, tu verras que certaines props n'existent pas, et que d'autres ont été commentées parce que jamais utilisées dans le code.

2023-05-31 14:53 UTC, PaulEntourage commented on src/pages/backoffice/candidat/[candidateId]/cv.tsx
> +    isRoleIncluded(COACH_USER_ROLES, userCompleteData.role) &&
Dis moi si je me trompe, mais

`if (
    isRoleIncluded(COACH_USER_ROLES, userCompleteData.role) &&
    !getRelatedUser(userCompleteData)
  ) {
    content = (
      <div className="uk-flex uk-flex-column uk-flex-middle">
        <h2 className="uk-text-bold uk-text-center">
          <span className="uk-text-primary">Aucun candidat</span> n&apos;est
          rattaché à ce compte.
        </h2>
        <p className="uk-text-center">
          Il peut y avoir plusieurs raisons à ce sujet. Contacte l&apos;équipe
          LinkedOut pour en savoir plus.
        </p>
      </div>
    );
  } `
    
On affiche "aucun candidat n'est rattaché à ce compte" s'il n'y a pas de relatedUser => c'est le relatedUser du coach, pas du candidat. 

Je vais rechecker en local quand même.

2023-05-31 14:54 UTC, PaulEntourage commented on src/pages/backoffice/candidat/[candidateId]/offres/index.tsx
>        (user !== prevUser ||
T'as raison, je corrige

2023-06-01 09:16 UTC, emile-bex commented on src/components/backoffice/admin/members/MemberList/useRole.ts
> +export function useRole(): UserRole {
Il me semble que justement il n'est pas exclusivement un `string` . Maintenant qu'on a les nouveaux roles externes, sur la page des membres, ça peut soit être un UserRole, soit être un UserRole[]. Dans le cas ou on choisit tous les candidats par exemple, il y a les deux paramètres dans l'URL : `role=Candidat&role=Candidat externe` ce qui fait qu'on va récupérer un tableau dans le router

2023-06-01 09:17 UTC, PaulEntourage commented on src/components/backoffice/admin/members/MemberList/useRole.ts
> +export function useRole(): UserRole {
Ok dans ce cas il faut modifier du code derrière parce qu'il est traité comme une chaine de caractère. Je vais regarder.

2023-06-01 09:18 UTC, emile-bex commented on src/components/filters/SearchBar.tsx
> +          // filters={filters}
Je crois que c'est des restes effectivement, j'avais du réorganiser les composants.

2023-06-01 09:18 UTC, emile-bex commented on src/components/filters/SearchBar.tsx
> +            // search={search}
Effectivement c'est des restes, on peut virer tout ça du coup je pense

2023-06-01 09:19 UTC, emile-bex commented on src/components/filters/SearchBar.tsx
> +  // numberOfResults,
Pareil on peut virer du coup je pense

2023-06-01 09:20 UTC, emile-bex commented on src/components/forms/FormWithValidation.tsx
> +                        // }}
On peut les virer du coup je pense

2023-06-01 09:20 UTC, emile-bex commented on src/utils/Finding.ts
> +  subset: UserRole | UserRole[] | string
Tu l'as enlevé du coup ? :)

2023-06-01 09:21 UTC, PaulEntourage commented on src/utils/Finding.ts
> +  subset: UserRole | UserRole[] | string
Oui :)

2023-06-01 09:23 UTC, emile-bex commented on src/pages/backoffice/candidat/[candidateId]/cv.tsx
> +    isRoleIncluded(COACH_USER_ROLES, userCompleteData.role) &&
Il me semble que le `userCompleteData` c'est le related user. Du coup là on check si le `relatedUser` c'est un candidat (donc le user actuel c'est un coach), donc on affiche l'erreur. Il faudrait du coup soit laisser comme c'était, soit modifier en `isRoleIncluded(COACH_USER_ROLES, user.role)`

2023-06-01 09:27 UTC, emile-bex commented on src/pages/backoffice/parametres.tsx
> +                  // }}
Ah oui parce que `UserInformationCard` c'est en fait les infos du user lié c'est ça ?

Pour le coach externe je comprends parce qu'on a une page spécifique pour ça, mais pourquoi pour le candidat externe on veut pas afficher les infos de son coach ?

2023-06-01 10:03 UTC, PaulEntourage commented on src/components/backoffice/admin/members/MemberList/useRole.ts
> +export function useRole(): UserRole {
En fait j'ai relu tout et c'est bon ca passe comme tableau autant que comme chaine de caractère, je sais pas ce qui m'a induit en erreur...

2023-06-01 10:04 UTC, PaulEntourage commented on src/components/backoffice/admin/members/MemberList/useRole.ts
> +export function useRole(): UserRole {
Du coup je corrige comme tu l'as suggéré.

2023-06-01 10:51 UTC, PaulEntourage commented on src/pages/backoffice/candidat/[candidateId]/cv.tsx
> +    isRoleIncluded(COACH_USER_ROLES, userCompleteData.role) &&
Ok ca marche je mets ce que tu proposes mais en fait le résultat est le même pour les coachs et candidats qui n'ont pas de relatedUser ^^'

2023-06-01 10:54 UTC, PaulEntourage commented on src/pages/backoffice/parametres.tsx
> +                  // }}
Oui t'as raison, y a pas de raison. Je l'ajoute

2023-06-01 15:13 UTC, emile-bex requested changes

2023-06-01 15:13 UTC, emile-bex commented on src/components/backoffice/candidate/CandidateOpportunities/CandidateOffersTab/CandidateOffersTab.tsx
> +interface CandidateOffersTabType {
Plutôt `CandidateOffersTabType`

2023-06-05 09:48 UTC, emile-bex approved these changes

2023-06-05 14:23 UTC, merged