[EN-6289] feat(cv): add formation fields experience
ReseauEntourage/entourage-job-front pull request #139
Opened 2023-07-27 14:20 UTC by PaulEntourage

2023-08-30 09:24 UTC, emile-bex requested changes

2023-08-30 09:24 UTC, emile-bex commented on src/components/backoffice/cv/TimelineCard/TimeLineList/TimeLineList.tsx
> +      className={`uk-list${items.length > 0 ? ' ent-list' : ''}`}
Pareil, il faudrait enlever UIkit ;)

2023-08-30 09:24 UTC, emile-bex commented on src/components/forms/schema/formEditExperience.json
Pourquoi ce fichier est en JSON encore ? Il devrait être en TS et ça devrait être un schema de type FormSchema<S> avec les validations

2023-08-30 09:24 UTC, emile-bex commented on src/components/utils/Inputs/DatePicker/DatePicker.tsx
> +  const valueToDisplay = value?.includes('T') ? value.slice(0, value.indexOf('T')) : value;
Mmmh, je ne rajouterais pas ça ici. Il faudrait plutôt que la date soit déjà au format `YYYY-MM-DD` quand tu le passe au DatePicker.

2023-08-30 09:24 UTC, emile-bex commented on src/utils/Sorting.ts
> +    return a.dateStart?.localeCompare(b.dateStart) > 0 ? -1 : 1;
Ici il faudrait plutôt utiliser Moment pour comparer les dates. `localeCompare` c'est spécifique aux chaînes de caractère. Même si ça marche, c'est pas forcément le plus compréhensible

2023-08-30 09:24 UTC, emile-bex commented on src/components/partials/CV/PageCvContent/PageCVContent.tsx
>                  {cv.experiences.map((experience) => {
Il faudrait vérifier si les expériences sont bien définis ;)

2023-08-30 09:24 UTC, emile-bex commented on src/components/partials/CV/PageCvContent/PageCVContent.tsx
> +  console.log(cv);
À retirer ;)

Pense bien à lancer les commandes `eslint` avant de pousser pour être sûr que tous ces trucs soit corrigé ;)

2023-08-30 09:24 UTC, emile-bex commented on src/components/forms/schemas/formEditFormation.ts
> +  ],
Il manque la propriété `isRequired` sur la plupart des champs non ? Il faudrait pas les rendre obligatoire sinon ça va poser soucis non ?

2023-08-30 10:43 UTC, PaulEntourage commented on src/components/backoffice/cv/TimelineCard/ExperiencesProfileCard/ExperiencesProfileCard.tsx
> +  onChange: (arg1: Partial<CV>) => void;
ok

2023-08-30 10:43 UTC, PaulEntourage commented on src/components/backoffice/cv/TimelineCard/FormationsProfileCard/FormationsProfileCard.tsx
> +  onChange: (arg1: Partial<CV>) => void;
ok

2023-08-30 10:43 UTC, PaulEntourage commented on src/components/backoffice/cv/TimelineCard/ExperiencesProfileCard/ExperiencesProfileCard.tsx
> +    setRemainingItems(5 - experiences.length);
ok

2023-08-30 10:43 UTC, PaulEntourage commented on src/components/backoffice/cv/TimelineCard/FormationsProfileCard/FormationsProfileCard.tsx
> +    setRemainingItems(3 - formations.length);
ok

2023-08-30 10:43 UTC, PaulEntourage commented on src/components/backoffice/cv/TimelineCard/TimeLineList/TimeLineItem/TimeLineItem.tsx
> +  onChange: (arg1: Partial<CV>) => void;
J'ai dû faire un truc un peu plus compliqué que ça ;)

2023-08-30 10:43 UTC, PaulEntourage commented on src/components/backoffice/cv/TimelineCard/TimeLineList/TimeLineItem/TimeLineItem.tsx
> +  type: string;
ok

2023-08-30 10:44 UTC, PaulEntourage commented on src/components/backoffice/cv/TimelineCard/TimeLineList/TimeLineItem/TimeLineItem.tsx
> +  }
Dans ce cas il n'y a plus trop de sens à avoir 2 tables séparées, il aurait juste fallu mettre une clé "type", mais là c'est un peu tard^^'

2023-08-30 10:45 UTC, PaulEntourage commented on src/components/backoffice/cv/TimelineCard/TimeLineList/TimeLineItem/TimeLineItem.tsx
> +          <p className="uk-margin-small-top uk-margin-small">
Je voulais pas toucher au style du backoffice...

2023-08-30 10:47 UTC, PaulEntourage commented on src/components/backoffice/cv/TimelineCard/TimeLineList/TimeLineList.tsx
> +  onChange: (arg1: any) => void;
ok

2023-08-30 10:48 UTC, PaulEntourage commented on src/components/backoffice/cv/TimelineCard/TimelineCard.tsx
> +  onChange: (arg1: any) => void;
ok

2023-08-30 10:48 UTC, PaulEntourage commented on src/components/backoffice/cv/TimelineCard/TimelineCard.tsx
> +  type: string;
ok

2023-08-30 12:00 UTC, PaulEntourage commented on src/components/backoffice/cv/TimelineCard/TimelineCard.tsx
> +    formSchema: AnyCantFix;
formSchema: typeof formEditExperience | typeof formEditFormation;

2023-08-30 12:01 UTC, PaulEntourage commented on src/components/backoffice/cv/TimelineCard/TimeLineList/TimeLineList.tsx
> +    formSchema: AnyCantFix;
idem

2023-08-30 12:08 UTC, PaulEntourage commented on src/components/backoffice/cv/TimelineCard/TimelineCard.tsx
> +        <h3 className="uk-card-title">{title}</h3>
idem: je n'ai pas touché au style

2023-08-30 12:35 UTC, PaulEntourage commented on src/components/backoffice/cv/TimelineCard/TimeLineList/TimeLineItem/TimeLineItem.tsx
> +    formSchema: AnyCantFix;
idem

2023-08-30 12:39 UTC, PaulEntourage commented on src/components/backoffice/cv/TimelineCard/TimelineCard.tsx
> +          Vous avez atteint le maximum des {type} à entrer
ok

2023-08-30 12:40 UTC, PaulEntourage commented on src/components/forms/FormSchema/FormSchema.types.ts
> +  | Date
OK là j'ai corrigé parce que c'était nécessaire pour le typage précis que tu m'as demandé de mettre en place plus haut, mais effectivement il faudra faire qqchose à ce sujet

2023-08-30 12:40 UTC, PaulEntourage commented on src/components/forms/schema/formEditExperience.json
deleted

2023-08-30 12:41 UTC, PaulEntourage commented on src/utils/Sorting.ts
> +    return a.dateStart?.localeCompare(b.dateStart) > 0 ? -1 : 1;
ok

2023-08-31 09:26 UTC, emile-bex commented on src/components/backoffice/cv/TimelineCard/TimelineCard.tsx
> +    formSchema: AnyCantFix;
Oui pardon

2023-08-31 09:28 UTC, emile-bex commented on src/components/forms/FormSchema/FormSchema.types.ts
> +  | Date
C'est pas juste parce que dans `api.types` il y a une type Date quelque part qu'on peut remplacer par `string` ? C'est quel code qui t'oblige à mettre ça ?

2023-08-31 09:29 UTC, emile-bex commented on src/components/utils/Inputs/DatePicker/DatePicker.tsx
> +  const valueToDisplay = value?.includes('T') ? value.slice(0, value.indexOf('T')) : value;
Mais du coup il n'y a pas besoin de cette transformation et donc de mettre `Date` dans le type `FieldValue` si ?

2023-09-01 12:46 UTC, PaulEntourage commented on src/components/forms/FormSchema/FormSchema.types.ts
> +  | Date
Non c'est bon j'ai retiré :)

2023-09-01 12:46 UTC, PaulEntourage commented on src/utils/Sorting.ts
> +    return a.dateStart?.localeCompare(b.dateStart) > 0 ? -1 : 1;
J'ai pas utilisé moment, juste les dates

2023-09-01 12:48 UTC, PaulEntourage commented on src/components/partials/CV/PageCvContent/PageCVContent.tsx
>                  {cv.experiences.map((experience) => {
ok

2023-09-01 12:49 UTC, PaulEntourage commented on src/components/partials/CV/PageCvContent/PageCVContent.tsx
> +  console.log(cv);
yes bien vu

2023-09-01 12:49 UTC, PaulEntourage commented on src/components/partials/CV/PageCvContent/PageCVContent.styles.tsx
> +  flex: 1 1 0%;
L'espace dans le container flex, que les éléments prennent toute la place qui leur attribuée

2023-09-04 08:28 UTC, merged