Feature/en 6259 backoffice admin offres
ReseauEntourage/entourage-job-front pull request #161
Opened 2023-10-26 16:10 UTC by PaulEntourage

2023-11-06 15:41 UTC, emile-bex requested changes

2023-11-06 15:41 UTC, emile-bex commented on src/components/backoffice/admin/AdminOpportunities/AdminOpportunities.styles.ts
> +    box-sizing: content-box;
Il vaut mieux utiliser des flex box c'est plus facile à gérer

2023-11-06 15:41 UTC, emile-bex commented on src/components/backoffice/admin/AdminOpportunities/AdminOpportunities.tsx
> +  }, [fetchData, filters, currentTag, hasFetchedAll, offset, search]);
Je me demande si on peut pas mutualiser le comportement avec la liste des offres côté candidat

2023-11-06 15:41 UTC, emile-bex commented on src/components/backoffice/admin/AdminOpportunities/AdminOpportunities.tsx
> +  useDeepCompareEffect(() => {
Pareil, est-ce qu'on peut pas mutualiser ?

2023-11-06 15:41 UTC, emile-bex commented on src/components/backoffice/admin/AdminOpportunities/AdminOpportunitiesFilters.types.ts
> +    value: adminOffersTags;
Ici comme dit au dessus, `adminOffersTags` devrait être un type `AdminOfferTag`

2023-11-06 15:41 UTC, emile-bex commented on src/components/backoffice/opportunities/OpportunitiesContainer/OpportunitiesList/CandidateOpportunitiesList/CandidateOpportunityItem/CandidateOpportunityItem.tsx
> +} from '../../OpportunitiesList.styles';
Attention à l'import relatif ;)

2023-11-06 15:41 UTC, emile-bex commented on src/components/backoffice/opportunities/OpportunitiesContainer/OpportunitiesList/OpportunitiesList.styles.ts
> +  -webkit-box-orient: vertical;
Pareil, ces styles là devrait être simplifié en utilisant des flexs

2023-11-06 15:41 UTC, emile-bex commented on src/hooks/useOpportunityList.ts
> +            // !!! to be fixed !!!
Pourquoi ça ne fonctionne pas ? on peut utiliser `moment` pour comparer les dates

2023-11-06 15:41 UTC, emile-bex commented on src/constants/index.ts
> +export type adminOffersTags = 'pending' | 'validated' | 'external' | 'archived';
Mettre `AdminOffersTag` si c'est un type

2023-11-06 15:41 UTC, emile-bex commented on src/constants/index.ts
> +export const ADMIN_OFFERS_TAGS = [
Et ici du coup ça devrait être un type `FilterConstant<AdminOffersTag>[]`

2023-11-06 15:41 UTC, emile-bex commented on src/components/backoffice/opportunities/OpportunitiesContainer/OpportunityDetails/useFetchOpportunity.ts
> +  function refreshOpportunity() {
Utiliser plutôt un `useCallback`

2023-11-06 15:41 UTC, emile-bex commented on src/components/backoffice/opportunities/OpportunitiesContainer/OpportunitiesList/AdminOpportunitiesList/AdminOpportunitiesList.tsx
> +import { useQueryParamsOpportunities } from '../../../useQueryParamsOpportunities';
Attention aux imports relatifs 😉

2023-11-06 15:41 UTC, emile-bex commented on src/components/backoffice/opportunities/OpportunitiesContainer/OpportunitiesList/AdminOpportunitiesList/AdminOpportunityItem/AdminOpportunityItem.tsx
> +import { ContractLabel } from '../../../ContractLabel';
Attention aux imports relatifs 😉

2023-11-06 15:41 UTC, emile-bex commented on src/components/backoffice/opportunities/OpportunitiesContainer/OpportunitiesList/AdminOpportunitiesList/AdminOpportunityItem/AdminOpportunityItem.tsx
> +} from '../../../OpportunitiesContainer.styles';
Attention aux imports relatifs 😉

2023-11-06 15:41 UTC, emile-bex commented on src/components/backoffice/opportunities/OpportunitiesContainer/OpportunitiesList/AdminOpportunitiesList/AdminOpportunityItem/AdminOpportunityItem.tsx
> +} from '../../OpportunitiesList.styles';
Attention aux imports relatifs 😉

2023-11-06 15:41 UTC, emile-bex commented on src/components/backoffice/opportunities/OpportunitiesContainer/OpportunityDetails/OpportunitySection/OpportunitySectionCandidates.tsx
> +  };
À mettre dans des constantes

2023-11-06 15:41 UTC, emile-bex commented on src/components/backoffice/opportunities/OpportunitiesContainer/OpportunityDetails/OpportunitySection/OpportunitySectionCandidates.tsx
> +      {opportunityUsers.map((opportunityuser) => {
Plutôt `opportunityUser`

2023-11-06 15:41 UTC, emile-bex commented on src/components/backoffice/opportunities/OpportunitiesContainer/OpportunityDetails/AdminOpportunityDetails/AdminOpportunityDetailsContainer.tsx
> +import { useOpportunityId } from '../../../useOpportunityId';
Attention aux imports relatifs 😉

2023-11-06 15:41 UTC, emile-bex commented on src/components/backoffice/opportunities/OpportunitiesContainer/OpportunityDetails/AdminOpportunityDetails/AdminOpportunityDetailsCTAs/AdminOpportunityDetailsCTAs.utils.tsx
> +export const CTAsByTag = [
Ici les tags devraient être dans un type : `AdminOffersTag`. Comme ça ton `CTAsByTag` peut être de type : `{ tag: AdminOffersTag, ctas: AdminOffersCTAs[] }[]`

2023-11-06 15:41 UTC, emile-bex commented on src/components/backoffice/opportunities/OpportunitiesContainer/OpportunityDetails/AdminOpportunityDetails/AdminOpportunityDetailsCTAs/AdminOpportunityDetailsCTAs.utils.tsx
> +export const allCTAs = {
Ici toutes les clefs devraient être dans un type : `type AdminOffersCTA = 'validate' | 'reject' | ...` et tes actions aussi `type AdminOffersAction = 'validateOpportunity' | ...`

Comme ça ton `AllCTAs` peut prendre le type : 
```
{ [K in AdminOffersCTA] : {
    color: string;
    className: string;
    action: AdminOffersAction,
    text: JSX.Element,
  }
```

2023-11-06 15:41 UTC, emile-bex commented on src/components/backoffice/opportunities/OpportunitiesContainer/OpportunityDetails/AdminOpportunityDetails/AdminOpportunityDetails.tsx
> +import { ContractLabel } from '../../ContractLabel';
Attention aux imports relatifs 😉

2023-11-06 15:41 UTC, emile-bex commented on src/components/backoffice/opportunities/OpportunitiesContainer/OpportunityDetails/AdminOpportunityDetails/AdminOpportunityDetails.tsx
> +
Tout ça ne devrait pas être dupliqué, ça devrait être mis dans un hook qui est utilisé part les deux listes

2023-11-06 15:41 UTC, emile-bex commented on src/components/backoffice/opportunities/OpportunitiesContainer/OpportunityDetails/AdminOpportunityDetails/AdminOpportunityDetailsCTAs/AdminOpportunityDetailsCTAs.tsx
> +  const updateOpportunity = async (
Mettre un `useCallback`

2023-11-06 15:41 UTC, emile-bex commented on src/components/backoffice/opportunities/OpportunitiesContainer/OpportunityDetails/AdminOpportunityDetails/AdminOpportunityDetailsCTAs/AdminOpportunityDetailsCTAs.tsx
> +  const updateExternalOpportunity = async (
Mettre un `useCallback`

2023-11-09 16:12 UTC, PaulEntourage commented on src/api/types.ts
> +  lastName?: string;
Parce que l'opportunité qui est récupérée par l'admin c'est l'objet AdminOpportunityWithOpportunityUsers qui est une extension de Opportunity, qui continuent un tableau d'OpportunityUser qui a un champ "user" dans lequel il y a un tableau de "UserCandidateWithUsers" qui a un firstName et un lastName.

2023-11-09 16:19 UTC, PaulEntourage commented on src/components/backoffice/admin/AdminOpportunities/AdminOffersTab/AdminOffersTab.utils.ts
> +  return value;
adminTabs c'est une constante; il n'y qu'un type dans le fichier, tu veux que je fasse quand même un fichier type?

2023-11-09 16:20 UTC, PaulEntourage commented on src/components/backoffice/admin/AdminOpportunities/AdminOffersTab/AdminOffersTab.utils.ts
> +  return value;
En revanche je peux la renommer ADMIN_TABS et les constantes de cette façon dans le fichier...

2023-11-09 16:21 UTC, PaulEntourage commented on src/components/backoffice/admin/AdminOpportunities/AdminOpportunities.styles.ts
> +    box-sizing: content-box;
ok

2023-11-09 16:31 UTC, PaulEntourage commented on src/components/backoffice/admin/AdminOpportunities/AdminOpportunitiesFilters.types.ts
> +    value: adminOffersTags;
Ok

2023-11-09 16:34 UTC, PaulEntourage commented on src/components/backoffice/opportunities/OpportunitiesContainer/OpportunitiesList/OpportunitiesList.styles.ts
> +  -webkit-box-orient: vertical;
C'est du code que tu as écrit il y a 9 mois, mais je peux le corriger sans souci! :)

2023-11-09 16:34 UTC, PaulEntourage commented on src/components/backoffice/opportunities/OpportunitiesContainer/OpportunitiesList/OpportunitiesList.styles.ts
> +  -webkit-box-orient: vertical;
Je me demande juste s'il n'y a pas une bonne raison de l'avoir écrit, tu t'en souviens?

2023-11-10 08:44 UTC, emile-bex commented on src/components/backoffice/admin/AdminOpportunities/AdminOffersTab/AdminOffersTab.utils.ts
> +  return value;
Dans ce cas renommer le fichier `.utils` en `.types` ? C'est un fichier de type au final

2023-11-10 08:48 UTC, emile-bex commented on src/components/backoffice/opportunities/OpportunitiesContainer/OpportunitiesList/OpportunitiesList.styles.ts
> +  -webkit-box-orient: vertical;
Haaan oui en fait je crois c'est pour qu'il y ai 3 lignes qui s'affichent seulement et qu'après ça parte en ellipsis

2023-11-10 09:47 UTC, PaulEntourage commented on src/components/backoffice/admin/AdminOpportunities/AdminOffersTab/AdminOffersTab.utils.ts
> +  return value;
ok

2023-11-10 09:50 UTC, PaulEntourage commented on src/components/backoffice/opportunities/OpportunitiesContainer/OpportunitiesList/CandidateOpportunitiesList/CandidateOpportunityItem/CandidateOpportunityItem.tsx
> +} from '../../OpportunitiesList.styles';
done

2023-11-10 09:50 UTC, PaulEntourage commented on src/hooks/useOpportunityList.ts
> +            // !!! to be fixed !!!
Il faut juste les transformer en date en fait, meme pas besoin de moment

2023-11-10 09:51 UTC, PaulEntourage commented on src/constants/index.ts
> +export type adminOffersTags = 'pending' | 'validated' | 'external' | 'archived';
done

2023-11-10 09:54 UTC, PaulEntourage commented on src/constants/index.ts
> +export const ADMIN_OFFERS_TAGS = [
done

2023-11-10 09:56 UTC, PaulEntourage commented on src/components/backoffice/opportunities/OpportunitiesContainer/OpportunityDetails/useFetchOpportunity.ts
> +  function refreshOpportunity() {
pour refreshOpportunity? Idem, c'est du code que je n'ai pas modifié, mais je peux l'ajouter

2023-11-10 09:58 UTC, PaulEntourage commented on src/components/backoffice/opportunities/OpportunitiesContainer/OpportunitiesList/AdminOpportunitiesList/AdminOpportunitiesList.tsx
> +import { useQueryParamsOpportunities } from '../../../useQueryParamsOpportunities';
done

2023-11-10 09:59 UTC, PaulEntourage commented on src/components/backoffice/opportunities/OpportunitiesContainer/OpportunitiesList/AdminOpportunitiesList/AdminOpportunityItem/AdminOpportunityItem.tsx
> +import { ContractLabel } from '../../../ContractLabel';
done

2023-11-10 10:08 UTC, PaulEntourage commented on src/components/backoffice/opportunities/OpportunitiesContainer/OpportunityDetails/AdminOpportunityDetails/AdminOpportunityDetailsContainer.tsx
> +import { useOpportunityId } from '../../../useOpportunityId';
done

2023-11-10 10:36 UTC, PaulEntourage commented on src/components/backoffice/opportunities/OpportunitiesContainer/OpportunityDetails/OpportunitySection/OpportunitySectionCandidates.tsx
> +      {opportunityUsers.map((opportunityuser) => {
yes

2023-11-10 10:45 UTC, PaulEntourage commented on src/components/backoffice/opportunities/OpportunitiesContainer/OpportunityDetails/AdminOpportunityDetails/AdminOpportunityDetailsCTAs/AdminOpportunityDetailsCTAs.utils.tsx
> +export const CTAsByTag = [
Ok je vois pas trop pourquoi on typerait une constante, mais c'est fait !

2023-11-10 11:14 UTC, PaulEntourage commented on src/components/backoffice/opportunities/OpportunitiesContainer/OpportunityDetails/AdminOpportunityDetails/AdminOpportunityDetailsCTAs/AdminOpportunityDetailsCTAs.utils.tsx
> +export const allCTAs = {
done

2023-11-10 11:15 UTC, PaulEntourage commented on src/components/backoffice/opportunities/OpportunitiesContainer/OpportunityDetails/AdminOpportunityDetails/AdminOpportunityDetails.tsx
> +import { ContractLabel } from '../../ContractLabel';
done

2023-11-10 11:50 UTC, PaulEntourage commented on src/components/backoffice/opportunities/OpportunitiesContainer/OpportunityDetails/AdminOpportunityDetails/AdminOpportunityDetails.tsx
> +
ok :)

2023-11-10 11:55 UTC, PaulEntourage commented on src/components/backoffice/opportunities/OpportunitiesContainer/OpportunityDetails/AdminOpportunityDetails/AdminOpportunityDetailsCTAs/AdminOpportunityDetailsCTAs.tsx
> +  const updateExternalOpportunity = async (
ok

2023-11-10 14:05 UTC, emile-bex commented on src/components/backoffice/opportunities/OpportunitiesContainer/OpportunityDetails/useFetchOpportunity.ts
> +  function refreshOpportunity() {
Ouais il vaut mieux ;)

2023-11-17 15:19 UTC, emile-bex submitted a review, later dismissed

2023-11-17 15:19 UTC, emile-bex commented on src/hooks/useOpportunityList.ts
> +            ...filtersToQueryParams(filtersToSend),
On peut pas mutualiser ces offset et limit avec la liste des offres du candidat ?

2023-11-17 15:19 UTC, emile-bex commented on src/hooks/useFilters.ts
> +    const tag = isAdmin ? originalQuery.tag : undefined;
Ici tu n'es pas censé mettre un paramètre "fonctionnel", le `isAdmin`. Le `useFilters est censé être entièrement générique. Je pense que c'est lié à mon autre commentaire plus bas sur l'utilisation de `useFilters`. Le paramètre `otherPathParams` te permet de noter les params que tu ne veux pas qu'ils soient effacé lors du reset, car ne sont des params indépendant des params de filtres.

2023-11-17 15:19 UTC, emile-bex commented on src/constants/index.ts
> +] as FilterConstant<AdminOffersTags>[];
Ici ne le mets pas en `as ...`, mets le plutôt en type de ta variable. `export const ADMIN_OFFERS_TAGS : FilterConstant<AdminOffersTags>[] =`

2023-11-17 15:19 UTC, emile-bex commented on src/constants/index.ts
> +];
Il faudrait mettre un `as const` sur toutes ces constantes pour bien typer

2023-11-17 15:19 UTC, emile-bex commented on src/components/backoffice/opportunities/OpportunitiesContainer/OpportunityDetails/OpportunitySection/OpportunitySectionCandidates.tsx
> +};
Pareil, tout ça il faut typer. Et utiliser un map de clef / valeurs pour ton `statusToTitle`

On a déjà dans des constantes les statuts et leur numéros associés

2023-11-17 15:19 UTC, emile-bex commented on src/components/backoffice/opportunities/OpportunitiesContainer/OpportunityDetails/CandidateOpportunityDetails/CandidateOpportunityDetails.tsx
> +    HEIGHTS,
Ici `height` c'est des constantes global donc pas besoin de le passer en paramètre de ton hook, le hook peut directement les récupérer. Et pareil, le `windowHeight` c'est la valeur qui vient du hook `window-size`, tu peux l'appeler directement dans le hook

2023-11-17 15:19 UTC, emile-bex commented on src/components/backoffice/opportunities/OpportunitiesContainer/OpportunityDetails/AdminOpportunityDetails/AdminOpportunityDetailsContainer.tsx
> +          oppRefreshCallback={() => {
Tu peux simplifier : `oppRefreshCallback={refreshOpportunity}`

2023-11-17 15:19 UTC, emile-bex commented on src/components/backoffice/opportunities/OpportunitiesContainer/OpportunityDetails/AdminOpportunityDetails/AdminOpportunityDetailsCTAs/AdminOpportunityDetailsCTAs.utils.tsx
> +] as CTAsByTagType;
Ici ne pas le mettre en `as ...` mais le mettre comme type de ta variable `const XXX : CTAsByTagType =`

2023-11-17 15:19 UTC, emile-bex commented on src/components/backoffice/opportunities/OpportunitiesContainer/OpportunityDetails/AdminOpportunityDetails/AdminOpportunityDetailsCTAs/AdminOpportunityDetailsCTAs.utils.tsx
> +} as AllCTAsType;
Ici ne pas le mettre en `as ...` mais le mettre comme type de ta variable `const AllCTAs : AllCTAsType =`

2023-11-17 15:19 UTC, emile-bex commented on src/components/backoffice/opportunities/OpportunitiesContainer/OpportunitiesList/AdminOpportunitiesList/AdminOpportunitiesList.tsx
> +  setOffset: Dispatch<SetStateAction<number>>;
Ici tu peux juste mettre `setOffset: () => void`

2023-11-17 15:19 UTC, emile-bex commented on src/components/backoffice/opportunities/OpportunitiesContainer/OpportunityDetails/AdminOpportunityDetails/AdminOpportunityDetails.tsx
> +          }}
Simplifier en `oppRefreshCallback={oppRefreshCallback}` et `fetchOpportunities={fetchOpportunities}`

2023-11-17 15:36 UTC, PaulEntourage commented on src/components/backoffice/admin/AdminOpportunities/AdminOffersTab/AdminOffersTab.types.ts
> +export const adminTabs = ADMIN_OFFERS_TAGS;
yes bien vu

2023-11-17 15:43 UTC, PaulEntourage commented on src/pages/backoffice/admin/offres/index.tsx
> +          console.log(params.department);
yes

2023-11-17 15:44 UTC, PaulEntourage commented on src/pages/backoffice/admin/offres/index.tsx
> +    [],
Ca changeait rien, et ajouter le "tag" faisait planter tout le script... on se retrouvait avec des valeurs indéfinies. J'ai pas trouvé comment corriger ça, donc j'ai fait la solution que tu as commenté plus bas là, qui n'est pas optimale mais qui marche

2023-11-17 15:48 UTC, PaulEntourage commented on src/hooks/useOpportunityList.ts
> +            ...filtersToQueryParams(filtersToSend),
Y a beaucoup de redite dans ces 2 hooks. On pourrait factoriser, comme on peut toujours, mais on va pas gagner de lignes de codes, je crois dans ce cas...

2023-11-17 15:48 UTC, PaulEntourage commented on src/hooks/useFilters.ts
> +    const tag = isAdmin ? originalQuery.tag : undefined;
cf plus haut

2023-11-17 15:53 UTC, PaulEntourage commented on src/constants/index.ts
> +] as FilterConstant<AdminOffersTags>[];
Ah oui j'avais pas vu ce commentaire. Du coup c'est corrigé ;)

2023-11-17 15:54 UTC, PaulEntourage commented on src/constants/index.ts
> +];
done

2023-11-17 16:12 UTC, PaulEntourage commented on src/components/backoffice/opportunities/OpportunitiesContainer/OpportunityDetails/OpportunitySection/OpportunitySectionCandidates.tsx
> +};
done :)

2023-11-17 16:13 UTC, PaulEntourage commented on src/components/backoffice/opportunities/OpportunitiesContainer/OpportunityDetails/CandidateOpportunityDetails/CandidateOpportunityDetails.tsx
> +    HEIGHTS,
Pour la Height, ca dépend justement de l'admin ou du candidat, c'est pas la même constante, donc je la garde en param, mais windows height t'as raison, je pensais l'avoir fait d'ailleurs.

2023-11-17 16:19 UTC, PaulEntourage commented on src/components/backoffice/opportunities/OpportunitiesContainer/OpportunityDetails/AdminOpportunityDetails/AdminOpportunityDetailsContainer.tsx
> +          oppRefreshCallback={() => {
bien vu

2023-11-17 16:20 UTC, PaulEntourage commented on src/components/backoffice/opportunities/OpportunitiesContainer/OpportunityDetails/AdminOpportunityDetails/AdminOpportunityDetailsCTAs/AdminOpportunityDetailsCTAs.utils.tsx
> +} as AllCTAsType;
yes done

2023-11-17 16:20 UTC, PaulEntourage commented on src/components/backoffice/opportunities/OpportunitiesContainer/OpportunityDetails/AdminOpportunityDetails/AdminOpportunityDetailsCTAs/AdminOpportunityDetailsCTAs.utils.tsx
> +] as CTAsByTagType;
yes done

2023-11-17 16:21 UTC, PaulEntourage commented on src/components/backoffice/opportunities/OpportunitiesContainer/OpportunityDetails/AdminOpportunityDetails/AdminOpportunityDetails.tsx
> +          }}
bien vu, done

2023-11-17 16:22 UTC, PaulEntourage commented on src/components/backoffice/opportunities/OpportunitiesContainer/OpportunitiesList/AdminOpportunitiesList/AdminOpportunitiesList.tsx
> +  setOffset: Dispatch<SetStateAction<number>>;
ok done

2023-11-21 17:00 UTC, PaulEntourage commented on src/components/backoffice/opportunities/OpportunitiesContainer/OpportunityDetails/AdminOpportunityDetails/AdminOpportunityDetailsCTAs/AdminOpportunityDetailsCTAs.tsx
> +  const updateOpportunity = async (
done

2023-11-21 17:02 UTC, PaulEntourage commented on src/components/backoffice/opportunities/OpportunitiesContainer/OpportunityDetails/useFetchOpportunity.ts
> +  function refreshOpportunity() {
ok

2023-11-28 16:02 UTC, PaulEntourage commented on src/components/backoffice/admin/AdminOpportunities/AdminOpportunities.tsx
> +          tag === previousTag))
t'as bien vérifié que ca marchait dans le chargement de la liste et le fait que ce soit bien le premier Opportunity de la dernière liste chargé qui soit sélectionné par défaut?

2023-11-28 16:03 UTC, PaulEntourage commented on src/components/backoffice/admin/AdminOpportunities/AdminOpportunities.tsx
> -    prevOffers,
On en a plus besoin dans la liste des dépendances?? pourtant il est utilisé dans la logique du useEffect

2023-11-28 16:05 UTC, PaulEntourage commented on src/components/backoffice/admin/AdminOpportunities/AdminOpportunities.tsx
> +          <Section className="custom-primary custom-fixed with-search-bar">
pourquoi avoir ajouté une section?

2023-11-28 16:07 UTC, PaulEntourage commented on src/components/backoffice/opportunities/OpportunitiesContainer/OpportunitiesList/AdminOpportunitiesList/AdminOpportunitiesList.tsx
> +  const opportunitiesListContent = opportunities.map((opportunity, index) => {
pourquoi créer une constante et ne pas faire le map dans le return ?

2023-11-28 16:08 UTC, PaulEntourage commented on src/components/backoffice/opportunities/OpportunitiesContainer/OpportunitiesList/AdminOpportunitiesList/AdminOpportunityItem/AdminOpportunityItem.tsx
> +  isSelected = false,
c'est aps false par défaut?

2023-11-28 16:16 UTC, PaulEntourage commented on src/components/backoffice/admin/organizations/OrganizationList/OrganizationList.tsx
> +          <Section className="custom-primary custom-fixed">
même remarque !

2023-11-28 16:40 UTC, emile-bex commented on src/components/backoffice/admin/AdminOpportunities/AdminOpportunities.tsx
> -    prevOffers,
Bien vu ;)

2023-11-28 16:40 UTC, emile-bex commented on src/components/backoffice/admin/AdminOpportunities/AdminOpportunities.tsx
> +          tag === previousTag))
Yes j'ai vérifier, j'ai repris ce qui était fait pour le candidat pour que ce soit ISO

2023-11-28 16:40 UTC, emile-bex commented on src/components/backoffice/opportunities/OpportunitiesContainer/OpportunitiesList/AdminOpportunitiesList/AdminOpportunityItem/AdminOpportunityItem.tsx
> +  isSelected = false,
C'est `undefined` si tu lui indiques pas de valeur par défaut, mais comme il est pas obligatoire, je préfère lui mettre une valeur par défaut même si ça change rien histoire de mieux comprendre qu'il n'est pas obligatoire

2023-11-28 16:40 UTC, emile-bex commented on src/components/backoffice/admin/members/MemberList/MemberList.tsx
> +          <Section className="custom-primary custom-fixed">
J'ai mis ces sections pour uniformiser les différentes barres de filtres et de search des différentes pages, pour pouvoir avoir également des padding communs et fixe pour mon calcul de hauteur dans le cas des offres. ET comme ça ils sont toute sticky ;)

2023-11-28 16:40 UTC, emile-bex commented on src/components/backoffice/opportunities/OpportunitiesContainer/OpportunitiesList/AdminOpportunitiesList/AdminOpportunitiesList.tsx
> +  const opportunitiesListContent = opportunities.map((opportunity, index) => {
C'était pour pouvoir le mémoiser à la base, mais aussi c'est un peu plus lisible je trouve ;) C'était pareil dans la version Candidat

2023-11-28 16:40 UTC, emile-bex commented on src/components/backoffice/admin/organizations/OrganizationList/OrganizationList.tsx
> +          <Section className="custom-primary custom-fixed">
J'ai mis ces sections pour uniformiser les différentes barres de filtres et de search des différentes pages, pour pouvoir avoir également des padding communs et fixe pour mon calcul de hauteur dans le cas des offres. ET comme ça ils sont toute sticky ;)

2023-11-28 16:40 UTC, emile-bex commented on src/components/backoffice/admin/AdminOpportunities/AdminOpportunities.tsx
> +          <Section className="custom-primary custom-fixed with-search-bar">
En gros j'ai juste uniformiser avec les autres bars de recherche et la barre surtout de dans la liste des offres du candidat. Ça permet d'avoir des paddings fix et d'avoir les bars en Sticky

2023-11-29 09:06 UTC, PaulEntourage commented on src/components/backoffice/opportunities/OpportunitiesContainer/OpportunitiesList/AdminOpportunitiesList/AdminOpportunitiesList.tsx
> +  const opportunitiesListContent = opportunities.map((opportunity, index) => {
Ok j'avoue que je préfère que le render des composants soit entièrement dans le return, mais c'est vraiment un détail.

2023-11-29 09:14 UTC, merged