[EN-6626] feat(lko2-profil): description and informations professionnelles
ReseauEntourage/entourage-job-front pull request #184
Opened 2023-12-28 13:57 UTC by PaulEntourage

2024-01-04 13:53 UTC, emile-bex requested changes

2024-01-04 13:53 UTC, emile-bex commented on src/components/backoffice/parametres/ParametresLayout/ProfessionalInformationCard/ProfessionalInformationCard.utils.tsx
> +      return { value: BL.value, label: BL.label };
Ici tu peux juste faire un `return findConstantFromValue(name, BUSINESS_LINES);`

2024-01-10 09:15 UTC, emile-bex requested changes

2024-01-10 09:15 UTC, emile-bex commented on src/components/backoffice/admin/members/MemberTable/Member/MemberToggle/MemberEmployedToggle.tsx
> +      title=""
C'est mieux de mettre un titre non ?

2024-01-10 09:15 UTC, emile-bex commented on src/components/backoffice/parametres/ParametresLayout/CVPreferences/CVPreferences.tsx
> +              dispatchOnSumbit={dispatchUpdateCandidate}
Petite typo

2024-01-10 09:15 UTC, emile-bex commented on src/components/backoffice/parametres/ParametresLayout/ParametresHelpCard/ParametresHelpModal/ParametresHelpModal.tsx
> +  const [tempProfile, setTempProfile] = useState<Partial<UserProfile>>({});
Ici, pour éviter le `!(helpField in tempProfile)`, est-ce que tu peux pas créer un type intermédiaire du style `Partial<UserProfile> & { helpField: { name: HelpValue }[] }` ?

Comme ça c'est plus lisible (on override pas le type `UserProfile`).

2024-01-10 09:15 UTC, emile-bex commented on src/components/backoffice/parametres/useConfirmationToaster.ts
> +    if (prevUpdateProfileStatus === ReduxRequestEvents.REQUESTED) {
Top !

2024-01-10 09:29 UTC, PaulEntourage commented on src/components/utils/Inputs/ToggleWithConfirmationModal/ToggleWithConfirmationModal.styles.tsx
> +const TEST = "19.5px";
Je sais pas, j'ai repris ce qu'il y avait dans le fichier Toggle.less

2024-01-10 09:30 UTC, PaulEntourage commented on src/components/utils/Button/Button.styles.ts
> +export const StyledButtonMock = styled.div`
Je me demande si on pourrait pas factoriser le code plutôt, je ne sais pas...

2024-01-10 09:31 UTC, PaulEntourage commented on src/components/backoffice/parametres/ParametresLayout/ProfessionalInformationCard/ProfessionalInformationCard.utils.tsx
> +      return { value: BL.value, label: BL.label };
Ah yes bien vu !

2024-01-10 09:32 UTC, PaulEntourage commented on src/components/utils/Inputs/ToggleWithModal/ToggleWithModal.tsx
> +                // edit form in Modal
Finalement non ;)

2024-01-10 09:33 UTC, PaulEntourage commented on src/components/utils/Inputs/ToggleWithModal/ToggleWithModal.styles.tsx
> +const TEST = '19.5px';
C'est le code existant que j'ai pas touché

2024-01-10 09:33 UTC, PaulEntourage commented on src/components/utils/Inputs/ToggleWithModal/ToggleWithModal.styles.tsx
> +const TEST = '19.5px';
Juste déplacé d'un fichier à l'autre

2024-01-10 09:34 UTC, PaulEntourage commented on src/use-cases/authentication/authentication.saga.ts
> +        error: 'UPDATE_FAILED',
Non, Guillaume n'en a pas fait, mais on peut le faire s'il faut.

2024-01-10 09:34 UTC, PaulEntourage commented on src/components/utils/Inputs/SelectList/SelectList.tsx
> +        onChange([...values, value]);
Oui t'as raison c'est mieux comme ça.

2024-01-10 09:35 UTC, PaulEntourage commented on src/components/utils/Inputs/SelectList/SelectList.tsx
> +        onChange([...values, value]);
Mais je dois toujours écouter values parce que la condition en dépend.

2024-01-10 09:38 UTC, PaulEntourage commented on src/components/utils/Inputs/SelectList/SelectList.tsx
> +  values?: AnyCantFix[]; // should be an array of strings
En fait en soi je peux pas typer parce que la valeur d'arrivée peut être n'importe quoi sous format de string (par exemple "BusinessLinesNames") => ca va planter si je mets "string[]"

2024-01-10 09:38 UTC, PaulEntourage commented on src/components/utils/Inputs/SelectList/SelectList.tsx
> +  onChange: (value: AnyCantFix[]) => void;
idem

2024-01-10 09:39 UTC, PaulEntourage commented on src/components/backoffice/admin/members/MemberTable/Member/MemberToggle/MemberEmployedToggle.tsx
> +      title=""
Non il n'y a pas de titre à cet endroit, c'était comme ça avant et tu comprends en voyant le design ;)

2024-01-10 09:39 UTC, PaulEntourage commented on src/components/backoffice/parametres/ParametresLayout/CVPreferences/CVPreferences.tsx
> +              dispatchOnSumbit={dispatchUpdateCandidate}
?

2024-01-10 13:46 UTC, emile-bex commented on src/components/backoffice/parametres/ParametresLayout/CVPreferences/CVPreferences.tsx
> +              dispatchOnSumbit={dispatchUpdateCandidate}
`dispatchOnSumbit` au lieu de `dispatchOnSubmit `

2024-01-10 16:10 UTC, PaulEntourage commented on src/components/backoffice/parametres/ParametresLayout/CVPreferences/CVPreferences.tsx
> +              dispatchOnSumbit={dispatchUpdateCandidate}
Waw bien vu haha

2024-01-11 09:29 UTC, emile-bex approved these changes

2024-01-11 09:29 UTC, emile-bex commented on src/components/backoffice/parametres/ParametresLayout/CVPreferences/CVModalEdit/CVModalEdit.tsx
> +      setCloseModal(true);
Du coup c'était pas plus simple de ne pas avoir le "state intermédiaire" `closeModal` ?

2024-01-11 09:29 UTC, emile-bex commented on src/components/backoffice/parametres/ParametresLayout/CVPreferences/CVModalConfirmation/CVModalConfirmation.tsx
> +  const [closeModal, setCloseModal] = React.useState<boolean>(false);
Du coup c'était pas plus simple de ne pas avoir le "state intermédiaire" `closeModal` ?

2024-01-11 09:30 UTC, merged