[EN-6714] feat(LKO2-profile-details): profile details contact form
ReseauEntourage/entourage-job-front pull request #194
Opened 2024-01-24 15:50 UTC by PaulEntourage

2024-01-25 08:37 UTC, emile-bex requested changes

2024-01-25 08:37 UTC, emile-bex commented on src/components/backoffice/profile/ProfileContactCard/ProfileContactCard.tsx
> +  const { selectedProfile } = useSelectedProfile();
Est-ce qu'on remonterais pas ça au niveau du parent ? Ou même au niveau de la page ? Genre dans `Profile.tsx` tu fais un `selectedProfile ? <Profile /> : <LoadingPage />`. Comme ça on est sûr que quand `ProfileContactCard` s'affiche on sait qu'on a le profile et ça évite le conditions au sein des composants. On peut même rajouter le système d'exception pour forcer le typage

2024-01-25 08:37 UTC, emile-bex commented on src/components/backoffice/profile/ProfileContactCard/ProfileContactCard.styles.tsx
> +  textarea {
On garde pas le style des TextArea qu'on a déjà ? Ce serait mieux non ?

2024-01-25 08:37 UTC, emile-bex commented on src/components/forms/schemas/formContactInternalMessage.ts
> +      placeholder: ' ',
Je mettrais quand même un placeholder genre 'Tapez votre message'

2024-01-25 08:37 UTC, emile-bex commented on src/components/backoffice/profile/ProfileContactCard/ProfileContactCard.tsx
> +    }
Ne pas oublier le `postInternalMessageReset` ici ;)

2024-01-25 09:09 UTC, PaulEntourage commented on src/components/backoffice/profile/ProfileContactCard/ProfileContactCard.tsx
> +  const { selectedProfile } = useSelectedProfile();
Oui on peut mais c'est juste que j'utilise le selector de redux plutôt que de passer des props dans les composants. C'est pas ce qu'on avait dit?

2024-01-25 09:10 UTC, PaulEntourage commented on src/components/backoffice/profile/ProfileContactCard/ProfileContactCard.styles.tsx
> +  textarea {
Les maquettes diffèrent et c'est une exception donc j'ai surchargé les inputs de ce form. 

J'ai essayé avec ce qu'on a et vraiment c'était moche ^^

Ca me choque pas qu'on surcharge dans des styled components particuliers, tant qu'on touche pas aux composants coeur.

2024-01-25 09:10 UTC, PaulEntourage commented on src/components/forms/schemas/formContactInternalMessage.ts
> +      placeholder: ' ',
Y en a pas dans les maquettes et honnêtement ça le fait.

2024-01-25 09:11 UTC, PaulEntourage commented on src/components/backoffice/profile/ProfileContactCard/ProfileContactCard.tsx
> +    }
Ah yes bien vu !

2024-01-29 15:20 UTC, emile-bex approved these changes

2024-01-29 16:37 UTC, merged