[EN-7050] Accentuer Optionnel et confidentiel
ReseauEntourage/entourage-job-front pull request #305
Opened 2024-07-03 14:55 UTC by guillobits

- Ajout d'un composant `Alert` qui pour le moment ne contient qu'une variant `info` qu'on pourra faire évoluer plus tard pour d'autres cas d'usage
- Ajout de ce composant dans le formulaire de registration
- Modification du libellé AAH en Allocation Adulte Handicapé

2024-07-04 09:33 UTC, DDZBX requested changes

2024-07-04 09:33 UTC, DDZBX commented on src/components/utils/Alert/Alert.tsx
> +export function Alert({ children, variant }: AlertProps) {
Meme si ce que t'as écrit est correct, est-ce qu'on peut se mettre d'accord pour utiliser la notation suivante: 
`export const Component = ({ props } : ComponentProps) => {}`

2024-07-04 09:33 UTC, DDZBX commented on src/components/utils/Alert/Alert.tsx
> +};
De la meme manière que mon premier commentaire, on pourra définir les valeurs par défaut dans l'objet des props avec `{ variant = 'info' }` directement dans la déclaration du composant.
Je sais qu'il existe des occurences dans le projet ou c'est défini comme ca mais c'est plutot la 'vieille' notation et ca serait bien qu'on s'accorde :)

2024-07-04 09:33 UTC, DDZBX commented on src/constants/styles.ts
> +      text: '#484848',
Est ce que la couleur du texte est variable en fonction de la variant ?

2024-07-04 14:15 UTC, guillobits commented on src/components/utils/Alert/Alert.tsx
> +export function Alert({ children, variant }: AlertProps) {
Oui complètement, je préfère même.
J'ai repris ce qui semblait être une majorité dans le code que j'ai vu.

2024-07-04 14:16 UTC, guillobits commented on src/components/utils/Alert/Alert.tsx
> +};
Pareil, ça me va à 200%

2024-07-04 14:18 UTC, guillobits commented on src/constants/styles.ts
> +      text: '#484848',
Oui, en fonction du variant passé il va utilisé la variable adéquate.

2024-07-08 09:03 UTC, DDZBX approved these changes
Super !
Félicitations pour ta première PR 🥇

2024-07-08 09:25 UTC, merged