[EN-7210] Fiche membre - voir le cv pro & cv perso
ReseauEntourage/entourage-job-front pull request #311
Opened 2024-07-16 07:57 UTC by guillobits

2024-07-17 13:50 UTC, DDZBX requested changes
J'ai pas remis tous les 'got' -> 'has'

2024-07-17 13:50 UTC, DDZBX commented on src/components/headers/HeaderProfile/HeaderProfile.desktop.tsx
> +  const openExternalCv = () => {
Si on pouvais etre régulier sur les majuscules du V ca serait super :p

2024-07-17 13:50 UTC, DDZBX commented on src/components/utils/Button/Button.tsx
> +  id?: string;
C'est pour les tests que t'as besoin d'un id ? Si oui il existe un tag 'dataTestId'

2024-07-18 09:31 UTC, guillobits commented on src/components/utils/Button/Button.tsx
> +  id?: string;
Non c'est pour le Dropdown je dois lui fournir un boundaryId d'un bouton, mais le bouton n'acceptait pas de recevoir un id.

2024-07-18 09:37 UTC, guillobits commented on src/components/headers/HeaderProfile/HeaderProfile.desktop.tsx
> +  const openExternalCv = () => {
Effectivement

2024-07-18 12:58 UTC, DDZBX approved these changes
Mon petit comment a regarder sinon c'est cool !

2024-07-18 12:58 UTC, DDZBX commented on src/components/utils/Button/Button.tsx
> +  id = 'button',
Ca peut poser problème si il y a plusieurs boutons sur une page non ?

2024-07-18 13:56 UTC, guillobits commented on src/components/utils/Button/Button.tsx
> +  id = 'button',
J'ai modifié pour faire mieux, même si ça n'aurait pas cassé ça sera mieux.

2024-07-18 14:08 UTC, merged