[EN-6995] Signaler un utilisateur
ReseauEntourage/entourage-job-front pull request #326
Opened 2024-08-16 10:06 UTC by guillobits

2024-08-30 14:01 UTC, DDZBX commented on src/api/api.ts
> +    return this.post(`/user/profile/${userId}/abuse`, userReportDto);
Peut etre uniformiser en report ?

2024-08-30 14:03 UTC, DDZBX commented on src/components/backoffice/profile/ProfileReportUserModal/ProfileReportUserModal.tsx
> +
Je prefererai qu'on stick avec les interfaces pour etre constant, les deux fonctionnent et il y a une légere diff entre les deux mais je pense que l'important c'est d'etre uniforme ?

2024-08-30 14:05 UTC, DDZBX commented on src/components/utils/Dropdown.tsx
> + */
Il y a beaucoup d'occurences de l'ancien dropdown ? Est ce que ca vaut le coup de les remplacer et supprimer l'ancien composant ?

2024-08-30 14:06 UTC, DDZBX requested changes
Voir commentaires

2024-08-30 14:18 UTC, guillobits commented on src/api/api.ts
> +    return this.post(`/user/profile/${userId}/abuse`, userReportDto);
Ouais ça sera mieux `report` ;)

2024-08-30 14:18 UTC, guillobits commented on src/components/utils/Dropdown.tsx
> + */
Oui il y'en a pas mal. Mais je l'ai remis dans le doc avec Alice donc on pourra faire un ticket spécifique pour faire ça. (mais ça sera simplifié car le nouveau existera déjà)

2024-09-19 13:12 UTC, DDZBX approved these changes
👍

2024-09-19 13:45 UTC, merged