refacto: condition hasMessage in Messaging
ReseauEntourage/entourage-job-front pull request #356
Opened 2024-10-14 08:26 UTC by guillobits

Prise en compte des retours sur la dernière PR front de la messagerie (la partie avec la condition).
De cette manière on test un `hasMessage` au lieu de la condition un peu complexe.

2024-10-14 09:47 UTC, DDZBX requested changes

2024-10-14 09:47 UTC, DDZBX commented on src/components/backoffice/messaging/Messaging.desktop.tsx
> +  const [hasMessage, setHasMessage] = React.useState(false);
`const [hasMessage, setHasMessage] = useState(false);`

2024-10-14 09:47 UTC, DDZBX commented on src/components/backoffice/messaging/Messaging.desktop.tsx
> +  const [hasMessage, setHasMessage] = React.useState(false);
On mix la gestion de state zustand et react, est ce que c'est une bonne idée sur le long terme ?

2024-10-14 10:25 UTC, guillobits commented on src/components/backoffice/messaging/Messaging.desktop.tsx
> +  const [hasMessage, setHasMessage] = React.useState(false);
Exact, c'est mieux avec l'import.
Oui pour moi, ce qui n'a pas besoin d'être dans un state plus global reste au sein d'un composant.
Justement sinon on se retrouve à complexifier le life cycle de l'app inutilement.

Pour moi, la régle c'est : est-ce que j'ai besoin de ce state ailleurs que dans mon composant ?
Si oui; go mettre dans le store
Si non; utiliser un state au sein du composant qui en a besoin

Qu'est-ce que tu en penses ?

2024-10-14 10:28 UTC, guillobits commented on src/components/backoffice/messaging/Messaging.desktop.tsx
> +  const [hasMessage, setHasMessage] = React.useState(false);
Et effectivement là, la question se pose quand même j'avais oublié on a deux composant pour mobile & desktop...
Je vais le mettre dans le store

2024-10-21 14:00 UTC, DDZBX approved these changes
💯

2024-10-21 14:37 UTC, merged