[EN-7457] Finalize refered user
ReseauEntourage/entourage-job-front pull request #376
Opened 2024-11-05 13:30 UTC by DDZBX

2024-11-05 15:41 UTC, guillobits requested changes
Quelques mini commentaires
Sinon très bien le fait d'auto-login à la fin, ça fait gagner une étape au candidat orienté.

2024-11-05 15:41 UTC, guillobits commented on src/components/finalize-refered-user/FinalizeReferedUserContainer/FinalizeReferedUserContainer.styles.tsx
> +// export const StyledFinalizeReferedUserRow = styled.div`
Est-ce que tu gardes ce commentaire ?

2024-11-05 15:41 UTC, guillobits commented on src/pages/finaliser-compte-oriente.tsx
> +};
Est-ce qu'il ne faudrait pas plutôt utiliser :
-   StyledRegistrationContainer,
-   StyledRegistrationFooter,
-   StyledRegistrationSpinnerContainer,
-   StyledRegistrationSubtitle,

C'est les composants qu'on utilise sur les autres pages liés à l'authentification

2024-11-05 15:41 UTC, guillobits commented on src/components/forms/schemas/formFinalizeReferedUser.ts
> +      id: 'setPassword',
Peut-être ajouter un showLabel: true, pour clarifier le rôle de chacun des inputs ?

2024-11-05 15:41 UTC, guillobits commented on src/components/forms/schemas/formFinalizeReferedUser.ts
> +      id: 'setPassword',
Comme ici :
https://www.figma.com/design/TVYUtyCO1mjJ2moDFvmzf2/Test---Entourage-Pro?node-id=1189-875&t=RhNXtSA4oGYTzMiS-4

2024-11-06 15:04 UTC, DDZBX commented on src/components/finalize-refered-user/FinalizeReferedUserContainer/FinalizeReferedUserContainer.styles.tsx
> +// export const StyledFinalizeReferedUserRow = styled.div`
nope :)

2024-11-06 15:53 UTC, DDZBX commented on src/pages/finaliser-compte-oriente.tsx
> +};
J'ai repris une partie et amélioré l'affichage pour mieux correspondre au designs

2024-11-06 15:53 UTC, DDZBX commented on src/components/forms/schemas/formFinalizeReferedUser.ts
> +      id: 'setPassword',
Yes bien vu

2024-11-07 08:58 UTC, guillobits approved these changes
Impec !

2024-11-07 14:39 UTC, merged